# Generated by Django 4.2.4 on 2024-01-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ban",
            field=models.BooleanField(default=False),
        ),
    ]
