# Generated by Django 4.2.4 on 2023-08-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_user_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="youtube_channel",
            new_name="youtube_handle",
        ),
    ]
