# Generated by Django 4.2.4 on 2023-09-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_alter_recipe_instructions"),
        ("account", "0009_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_recipes",
            field=models.ManyToManyField(
                related_name="favorited_by", to="recipe.recipe"
            ),
        ),
    ]
