# Generated by Django 4.2.4 on 2023-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("North America", "NORTH_AMERICA"),
                    ("South America", "SOUTH_AMERICA"),
                    ("Europe", "EUROPE"),
                    ("Eastern Europe", "EASTERN_EUROPE"),
                    ("Western Europe", "WESTERN_EUROPE"),
                    ("Asia", "ASIA"),
                    ("East Asia", "EAST_ASIA"),
                    ("South Asia", "SOUTH_ASIA"),
                    ("Southeast Asia", "SOUTHEAST_ASIA"),
                    ("Africa", "AFRICA"),
                    ("North Africa", "NORTH_AFRICA"),
                    ("Sub-Saharan Africa", "SUB_SAHARAN_AFRICA"),
                    ("Oceania", "OCEANIA"),
                    ("Australia", "AUSTRALIA"),
                    ("New Zealand", "NEW_ZEALAND"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("recipe", "RECIPE"),
                    ("health", "HEALTH"),
                    ("cosmetic", "COSMETIC"),
                ],
                default="recipe",
                max_length=20,
            ),
        ),
    ]
