# Generated by Django 4.2.4 on 2023-08-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_recipe_origin_alter_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("recipe", "RECIPE"),
                    ("health", "HEALTH"),
                    ("cosmetic", "COSMETIC"),
                    ("garden", "GARDEN"),
                    ("home", "HOME"),
                    ("fermentaion", "FERMENTAION"),
                    ("juice", "JUICE"),
                ],
                default="recipe",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipe.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
    ]
