# Generated by Django 4.2.4 on 2023-08-30 16:49

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_recipe_slug_recipe_url_link_recipestep_youtube_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to="profile_pictures",
            ),
        ),
    ]
