# Generated by Django 4.2.4 on 2023-09-15 07:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_delete_recipestep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
