# Generated by Django 4.2.4 on 2023-09-15 13:00

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_alter_recipe_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuillPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=django_quill.fields.QuillField(),
        ),
    ]
