# Generated by Django 4.2.4 on 2023-09-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0009_quillpost_alter_recipe_instructions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="durations",
            new_name="duration",
        ),
    ]
