# Generated by Django 4.2.4 on 2023-09-17 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_recipe_duration_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="duration_type",
            new_name="duration_scale",
        ),
    ]
