# Generated by Django 4.2.4 on 2023-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0013_rename_duration_type_recipe_duration_scale"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuillPost",
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gramme", "GRAMME"),
                    ("Kilograme", "KILOGRAME"),
                    ("Spoon", "SPOON"),
                    ("Liter", "LITER"),
                    ("A tiny bit", "ATINYBIT"),
                    ("Piece", "PIECE"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
