# Generated by Django 4.2.4 on 2023-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0016_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
