# Generated by Django 4.2.4 on 2023-12-01 12:22

import common.models
import django.core.validators
import django.db.models.deletion
import pictures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("edited", models.BooleanField(default=False)),
                ("edtied_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    pictures.models.PictureField(
                        aspect_ratios=[None, "1/1", "3/2", "16/9"],
                        breakpoints={
                            "l": 1200,
                            "m": 992,
                            "s": 768,
                            "xl": 1400,
                            "xs": 576,
                        },
                        container_width=1200,
                        file_types=["WEBP"],
                        grid_columns=12,
                        height_field="height",
                        pixel_densities=[1, 2],
                        storage=common.models.CustomS3Boto3Storage(),
                        upload_to=common.models.image_upload_path,
                        width_field="width",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("article", "Article"),
                            ("recipe", "Recipe"),
                            ("recipe step", "RecipeStep"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Youtube", "YOUTUBE"),
                            ("Twitter", "TWITTER"),
                            ("Instagram", "INSTAGRAM"),
                            ("Facebook", "FACEBOOK"),
                            ("Tiktok", "TIKTOK"),
                            ("Website", "WEBSITE"),
                        ],
                        default="Youtube",
                        max_length=20,
                    ),
                ),
                ("embedded", models.BooleanField(default=False)),
                ("object_id", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "value",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
