# Generated by Django 4.2.4 on 2023-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_abuse"),
    ]

    operations = [
        migrations.AddField(
            model_name="abuse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
