# Generated by Django 4.2.4 on 2023-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_abuse_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="abuse",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
