# Generated by Django 4.2.4 on 2023-12-08 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0003_remove_recipe_image"),
        ("article", "0003_remove_article_image"),
        ("common", "0004_image_articles_image_recipes_image_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="articles",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="article.article",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="recipes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="users",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_picture",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
