# Generated by Django 4.2.4 on 2023-12-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_image_articles_alter_image_recipes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="articles",
        ),
        migrations.RemoveField(
            model_name="image",
            name="recipes",
        ),
        migrations.RemoveField(
            model_name="image",
            name="users",
        ),
    ]
