# Generated by Django 4.2.4 on 2023-11-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0005_abuse_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Abuse",
            new_name="Report",
        ),
    ]
