# Generated by Django 4.2.4 on 2023-12-17 07:39

import common.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_remove_rate_recipe_rate_content_type_rate_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Image Height"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(
                height_field="height",
                storage=common.models.CustomS3Boto3Storage(),
                upload_to=common.models.image_upload_path,
                verbose_name="Image",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Image Width"
            ),
        ),
    ]
