# Generated by Django 4.2.4 on 2023-11-23 21:31

import common.models
import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_report_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=pictures.models.PictureField(
                aspect_ratios=[None, "1/1", "3/2", "16/9"],
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                pixel_densities=[1, 2],
                storage=common.models.CustomS3Boto3Storage(),
                upload_to=common.models.image_upload_path,
            ),
        ),
    ]
