# Generated by Django 4.2.4 on 2023-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_image_type_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='embedded',
            field=models.BooleanField(default=False),
        ),
    ]
