# Generated by Django 4.2.4 on 2023-11-03 07:57

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
from recipe.models import Recipe


def set_content_type(apps, schema_editor):
    Comment = apps.get_model("recipe", "Comment")
    ct = ContentType.objects.get_for_model(Recipe)
    Comment.objects.update(content_type=ct)


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                to="contenttypes.ContentType",
                on_delete=models.CASCADE,
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_content_type),
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                to="contenttypes.ContentType",
                on_delete=models.CASCADE,
            ),
        ),
    ]
