# Generated by Django 4.2.4 on 2023-11-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='url_link',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='website',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='youtube',
        ),
        migrations.CreateModel(
            name='RecipeStps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('recipe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_step', to='recipe.recipe')),
            ],
        ),
    ]
