# Generated by Django 4.2.4 on 2023-12-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_recipestep_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
    ]
