# Generated by Django 4.2.4 on 2023-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_alter_recipe_category_recipestep"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="url_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipestep",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="youtube_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
