# Generated by Django 4.2.4 on 2023-11-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_link_embedded'),
        ('recipe', '0004_recipestep_delete_recipestps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ['step_number']},
        ),
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.image'),
        ),
    ]
