# Generated by Django 4.2.4 on 2023-08-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="durations",
            field=models.IntegerField(default=10),
        ),
    ]
