# Generated by Django 4.2.4 on 2023-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0010_rename_durations_recipe_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="youtube_link",
            new_name="facebook",
        ),
        migrations.AddField(
            model_name="recipe",
            name="instagram",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tiktok",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="twitter",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="youtube",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Recipe", "RECIPE"),
                    ("Health", "HEALTH"),
                    ("Cosmetic", "COSMETIC"),
                    ("Garden", "GARDEN"),
                    ("Home", "HOME"),
                    ("Fermentaion", "FERMENTAION"),
                    ("Animal", "ANIMAL"),
                    ("Juice", "JUICE"),
                ],
                default="Recipe",
                max_length=20,
            ),
        ),
    ]
