# Generated by Django 4.2.4 on 2023-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipe",
            "0011_rename_youtube_link_recipe_facebook_recipe_instagram_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="duration_type",
            field=models.CharField(
                choices=[
                    ("Minute", "MINUTE"),
                    ("Hour", "HOUR"),
                    ("Day", "DAY"),
                    ("Week", "WEEK"),
                    ("Month", "MONTH"),
                    ("Year", "YEAR"),
                ],
                default="Minute",
                max_length=20,
            ),
        ),
    ]
