# Generated by Django 4.2.4 on 2023-09-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0014_delete_quillpost_alter_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="image_base64_or_svg",
            field=models.TextField(blank=True),
        ),
    ]
