# Generated by Django 4.2.4 on 2023-09-23 16:13

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0019_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
