# Generated by Django 4.2.4 on 2023-10-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0021_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
