# Generated by Django 4.2.4 on 2023-10-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0022_rename_user_comment_author_remove_recipe_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="edtied_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
