FROM python:3.11

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt update
RUN apt install -y postgresql 
RUN pip install --upgrade pip
# COPY ./requirements.txt .
# RUN pip install -r requirements.txt

RUN pip install django==4.2
RUN pip install psycopg2
# RUN pip install b2sdk
RUN pip uninstall PIL
RUN pip uninstall django-easy-audit
RUN pip uninstall htmx
RUN pip uninstall quill-editor
RUN pip uninstall storages
RUN pip uninstall versatileimagefield
RUN pip uninstall gunicorn
RUN pip install django-versatileimagefield


# DEV
RUN pip uninstall django-tailwind
RUN pip uninstall pattern_library



# RUN python mannage.py compilemessages

COPY . .

CMD ["gunicorn","elisasrecipe.wsgi"]
