# Generated by Django 4.2.4 on 2023-11-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("article", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="common.tag"
            ),
        ),
    ]
