# Generated by Django 4.2.4 on 2023-12-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
    ]
