# Generated by Django 4.2.4 on 2023-12-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
