# Generated by Django 4.2.9 on 2024-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_articles",
            field=models.ManyToManyField(
                related_name="favorite_articles", to="article.article"
            ),
        ),
    ]
