# Generated by Django 4.2.4 on 2023-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_articles",
            field=models.ManyToManyField(
                related_name="favorite_articles", to="article.article"
            ),
        ),
    ]
