# Generated by Django 4.2.4 on 2023-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_handle",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_handle",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_handle",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_channel",
            field=models.URLField(blank=True),
        ),
    ]
