# Generated by Django 4.2.4 on 2023-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipe_slug_recipe_url_link_recipestep_youtube_link_and_more"),
        ("account", "0005_alter_passwordresettoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="favorited_by", to="recipe.recipe"
            ),
        ),
    ]
