# Generated by Django 4.2.4 on 2023-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
        ("account", "0006_article_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_articles",
            field=models.ManyToManyField(
                related_name="favorite_articles", to="recipe.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorite_recipes",
            field=models.ManyToManyField(
                related_name="favorite_recipes", to="recipe.recipe"
            ),
        ),
    ]
