# Generated by Django 4.2.4 on 2023-08-29 05:00

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_favorite_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to="profile_pictures",
            ),
        ),
    ]
