# Generated by Django 4.2.4 on 2023-11-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_tag_remove_comment_recipe_comment_object_id_and_more"),
        ("account", "0007_user_favorite_articles_alter_user_favorite_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="recipe.tag"),
        ),
    ]
