# Generated by Django 4.2.4 on 2023-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_articles",
            field=models.ManyToManyField(
                related_name="favorite_articles", to="account.article"
            ),
        ),
    ]
