# Generated by Django 4.2.4 on 2023-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_user_favorite_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tiktok_handle",
            field=models.URLField(blank=True),
        ),
    ]
