# Generated by Django 4.2.4 on 2023-10-09 06:48

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_user_tiktok_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to="profile_pictures",
            ),
        ),
    ]
