# Generated by Django 4.2.4 on 2023-10-16 06:51

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_blogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentry",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="edtied_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to="blog_images",
            ),
        ),
    ]
