# Generated by Django 4.2.4 on 2023-10-17 06:42

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_article_delete_blogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
